extends:
  - standard-with-typescript
  - prettier
ignorePatterns:
  - dist
plugins:
  - 'jest-formatting'
rules:
  '@typescript-eslint/strict-boolean-expressions': off
  '@typescript-eslint/restrict-template-expressions': off
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/require-array-sort-compare': off
  'jest-formatting/padding-around-describe-blocks': warn
  'jest-formatting/padding-around-test-blocks': warn
overrides:
  - files: '*.ts'
    parserOptions:
      project: ./tsconfig.json
    rules:
      '@typescript-eslint/no-unused-vars':
        - error
        - argsIgnorePattern: '^_'
          varsIgnorePattern: '^_'
