AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for Chatbot to alert engineers

Parameters:
  SlackChannelId:
    Description: Slack channel ID for alerts
    Type: String
  SlackWorkspaceId:
    Description: Slack workspace ID for channel
    Type: String
  SnsTopicArn:
    Description: Amazon Resource Name for Simple Notification Service topic to which CloudWatch alarms are published
    Type: String

Resources:
  Chatbot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName:
        # di-btm-alert-chatbot-<unique ID>
        !Join [
          "-",
          [
            "di-btm-alert-chatbot",
            !Select [
              4,
              !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]],
            ],
          ],
        ]
      IamRoleArn: !GetAtt Role.Arn
      SlackChannelId: !Ref SlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SnsTopicArns:
        - !Ref SnsTopicArn

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: chatbot.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
