version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "di-billing-transaction-monitoring"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1h6qgs4rg2fke"
s3_prefix = "di-billing-transaction-monitoring"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=\"dev\" VpcStackName=\"vpc\""
