AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for infrastructure to monitor user identity verification events for billing purposes
Transform: AWS::Serverless-2016-10-31

Parameters:
  Prefix:
    Type: String
    Default: di-btm
  Environment:
    Description: Environment type
    Type: String
    Default: dev
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none

Conditions:
  UseCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, none]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]
  IsLocal: !Equals [!Ref Environment, local]
  IsDev: !Equals [!Ref Environment, dev]
  IsBuild: !Equals [!Ref Environment, build]
  IsStaging: !Equals [!Ref Environment, staging]
  IsIntegration: !Equals [!Ref Environment, integration]
  IsProduction: !Equals [!Ref Environment, production]
  IsNotProduction: !Not [!Equals [!Ref Environment, production]]
  IsLowerEnv:
    !Not [
      !Or [
        !Equals [!Ref Environment, production],
        !Equals [!Ref Environment, staging],
        !Equals [!Ref Environment, integration],
      ],
    ]
  IsHigherEnv:
    !Or [
      !Equals [!Ref Environment, production],
      !Equals [!Ref Environment, staging],
      !Equals [!Ref Environment, integration],
    ]

Mappings:
  Environments:
    dev:
      TransactionInputQueueArn: none
      TransactionInputDLQArn: none
      TransactionInputKMSKeyArn: none
    build:
      TransactionInputQueueArn: none
      TransactionInputDLQArn: none
      TransactionInputKMSKeyArn: none
    staging:
      TransactionInputQueueArn: arn:aws:sqs:eu-west-2:178023842775:PublishToBillingSQSQueue-staging
      TransactionInputDLQArn: arn:aws:sqs:eu-west-2:178023842775:PublishToBillingSQSDLQueue-staging
      TransactionInputKMSKeyArn: arn:aws:kms:eu-west-2:178023842775:key/a9d351bb-92f6-4209-b821-78f10474b879
    integration:
      TransactionInputQueueArn: arn:aws:sqs:eu-west-2:729485541398:PublishToBillingSQSQueue-integration
      TransactionInputDLQArn: arn:aws:sqs:eu-west-2:729485541398:PublishToBillingSQSDLQueue-integration
      TransactionInputKMSKeyArn: arn:aws:kms:eu-west-2:729485541398:key/6abc512a-ca28-4a81-8576-ac7f47a92e72
    production:
      TransactionInputQueueArn: arn:aws:sqs:eu-west-2:123456789012:PublishToBillingSQSQueue-production
      TransactionInputDLQArn: arn:aws:sqs:eu-west-2:123456789012:PublishToBillingSQSDLQueue-production
      TransactionInputKMSKeyArn: arn:aws:kms:eu-west-2:123456789012:key/12345678-1234-1234-1234-123456789012

Globals:
  Function:
    CodeSigningConfigArn:
      !If [UseCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]
    KmsKeyArn: !GetAtt KmsKey.Arn
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    Runtime: nodejs16.x
    Timeout: 30
    CodeUri: dist/

Resources: !YAMLInclude ./cloudformation/global.yaml,
  ./cloudformation/test-only.yaml,
  ./cloudformation/filtering.yaml,
  ./cloudformation/cleaning.yaml,
  ./cloudformation/transaction-storage.yaml,
  ./cloudformation/config-store.yaml#NO_LOCAL,
  ./cloudformation/custom-s3-object-resource.yaml#NO_LOCAL,
  ./cloudformation/raw-invoice-textract-data-store.yaml,
  ./cloudformation/raw-invoice-pdf-store.yaml,
  ./cloudformation/test-invoice-pdf-store.yaml,
  ./cloudformation/standardised-invoice-storage.yaml,
  ./cloudformation/extraction.yaml,
  ./cloudformation/calculation-s3.yaml,
  ./cloudformation/calculation-athena.yaml#NO_LOCAL,
  ./cloudformation/custom-athena-view-resource.yaml#NO_LOCAL,
  ./cloudformation/invoice-athena.yaml#NO_LOCAL

Outputs:
  SnsAlarmTopicArn:
    Description: Amazon Resource Name for Simple Notification Service topic to which CloudWatch alarms are published
    Value: !Ref AlarmTopic
