AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for infrastructure to monitor user identity verification events for billing purposes
Transform: AWS::Serverless-2016-10-31

Parameters:
  Prefix:
    Type: String
    Default: di-btm
  Environment:
    Description: Environment type
    Type: String
    Default: dev
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none

Conditions:
  UseCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, none]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]
  IsLocal: !Equals [!Ref Environment, 'local']
  IsNotProduction: !Not [!Equals [!Ref Environment, production]]

Globals:
  Function:
    CodeSigningConfigArn:
      !If [UseCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]
    KmsKeyArn: !GetAtt KmsKey.Arn
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    Runtime: nodejs16.x
    Timeout: 30
    CodeUri: dist/

Resources: !YAMLInclude ./cloudformation/global.yaml,
  ./cloudformation/athena.yaml#NO_LOCAL,
  ./cloudformation/test-only.yaml,
  ./cloudformation/filtering.yaml,
  ./cloudformation/cleaning.yaml,
  ./cloudformation/calculation.yaml,
  ./cloudformation/transaction-storage.yaml,
  ./cloudformation/config-store.yaml#NO_LOCAL,
  ./cloudformation/custom-s3-object-resource.yaml#NO_LOCAL,
  ./cloudformation/raw-invoice-textract-data-store.yaml,
  ./cloudformation/raw-invoice-pdf-store.yaml,
  ./cloudformation/test-invoice-pdf-store.yaml,
  ./cloudformation/standardised-invoice-storage.yaml,
  ./cloudformation/extraction.yaml

Outputs:
  SnsAlarmTopicArn:
    Description: Amazon Resource Name for Simple Notification Service topic to which CloudWatch alarms are published
    Value: !Ref AlarmTopic
