AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for infrastructure to monitor user identity verification events for billing purposes
Transform: AWS::Serverless-2016-10-31

Parameters:
  AlertSlackChannelId:
    Description: Slack channel ID for alerts to support engineers
    Type: String
    Default: dummy-alert-slack-channel-id
  AlertSlackWorkspaceId:
    Description: Slack workspace ID for above channel
    Type: String
    Default: dummy-alert-slack-workspace-id
  CodeSigningConfigArn:
    Description: ARN of Code Signing Config from deployment pipeline
    Type: String
    Default: none
  Environment:
    Description: Environment type
    Type: String
    Default: dev
    AllowedValues:
      - local
      - dev
      - build
      - staging
      - integration
      - production
  PermissionsBoundary:
    Description: ARN of permissions boundary for new roles
    Type: String
    Default: none

Conditions:
  UseCodeSigning: !Not [!Equals [!Ref CodeSigningConfigArn, none]]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, none]]
  IsLocal: !Equals [!Ref Environment, "local"]

Globals:
  Function:
    CodeSigningConfigArn:
      !If [UseCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue]
    KmsKeyArn: !GetAtt KmsKey.Arn
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
    Runtime: nodejs16.x
    Timeout: 30
    CodeUri: dist/

Resources: !YAMLInclude ./cloudformation/global.yaml,
  ./cloudformation/test-only.yaml,
  ./cloudformation/filtering.yaml,
  ./cloudformation/cleaning.yaml,
  ./cloudformation/storage.yaml,
  ./cloudformation/athena.yaml#NO_LOCAL,
  ./cloudformation/config-store.yaml#NO_LOCAL,
  ./cloudformation/custom-s3-object-resource.yaml#NO_LOCAL,
  ./cloudformation/alerting.yaml#NO_LOCAL
  ./cloudformation/raw-invoice-pdf-store.yaml
