SlackAlertChatbot:
  Type: AWS::Chatbot::SlackChannelConfiguration
  Properties:
    ConfigurationName: # di-btm-slack-alert-chatbot-<unique ID>
      !Join [
        "-",
        [
          "di-btm-slack-alert-chatbot",
          !Select [
            4,
            !Split ["-", !Select [2, !Split ["/", !Ref AWS::StackId]]],
          ],
        ],
      ]
    IamRoleArn: !GetAtt SlackAlertChatbotRole.Arn
    SlackChannelId: !Ref AlertSlackChannelId
    SlackWorkspaceId: !Ref AlertSlackWorkspaceId
    SnsTopicArns:
      - !Ref AlarmTopic

SlackAlertChatbotRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: chatbot.amazonaws.com
    ManagedPolicyArns:
      - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
