AWSTemplateFormatVersion: '2010-09-09'

Resources:
  CalculationsDB:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub ${AWS::StackName}-calculations

  MonthlyExtractTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CalculationsDB
      TableInput:
        Name: btm_monthly_extract
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: true
          storage.location.template: !Sub s3://${StorageBucket}/btm_extract_data/full-extract.json
        StorageDescriptor:
          Columns:
            - Name: vendor_id
              Type: string
            - Name: vendor_name
              Type: string
            - Name: service_name
              Type: string
            - Name: year
              Type: string
            - Name: month
              Type: string
            - Name: billing_price_formatted
              Type: string
            - Name: transaction_price_formatted
              Type: string
            - Name: price_difference
              Type: string
            - Name: billing_amount_with_tax
              Type: string
            - Name: price_difference_percentage
              Type: double
          Compressed: true
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${StorageBucket}/btm_extract_data/
          StoredAsSubDirectories: false
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              ignore.malformed.json: true
              serialization.format: 1
              field.delim: ','
              timestamp.formats: yyyy-MM-dd
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe

  TransactionTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CalculationsDB
      TableInput:
        Name: btm_transactions_standardised
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: true
          partition_filtering.enabled: true
          projection.enabled: true
          projection.year.type: integer
          projection.year.range: 2005,2050
          projection.month.type: integer
          projection.month.digits: 2
          projection.month.range: 1,12
          storage.location.template:
            !Join [
              '',
              ['s3://', !Ref StorageBucket, '/btm_event_data/${year}/${month}'],
            ]
        PartitionKeys:
          - { Name: year, Type: string }
          - { Name: month, Type: string }
        StorageDescriptor:
          Columns:
            - Name: vendor_id
              Type: string
            - Name: event_id
              Type: string
            - Name: event_name
              Type: string
            - Name: timestamp
              Type: timestamp
            - Name: timestamp_formatted
              Type: string
            - Name: component_id
              Type: string
            - Name: credits
              Type: int
          Compressed: true
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${StorageBucket}/btm_event_data/
          StoredAsSubDirectories: false
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              ignore.malformed.json: true
              serialization.format: 1
              field.delim: ''
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe

  RateTableTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CalculationsDB
      TableInput:
        Name: btm_rates_standardised
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: true
          storage.location.template: !Sub s3://${ConfigStackParameter.Value}/rate_tables/rates.csv
        StorageDescriptor:
          Columns:
            - Name: vendor_id
              Type: string
            - Name: event_name
              Type: string
            - Name: volumes_from
              Type: int
            - Name: volumes_to
              Type: int
            - Name: unit_price
              Type: decimal(12,4)
            - Name: effective_from
              Type: date
            - Name: effective_to
              Type: date
          Compressed: true
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${ConfigStackParameter.Value}/rate_tables/
          StoredAsSubDirectories: false
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              field.delim: ','
              skip.header.line.count: 1
              timestamp.formats: yyyy-MM-dd
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe

  VendorServiceMappingTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CalculationsDB
      TableInput:
        Name: btm_vendor_service_standardised
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: true
          storage.location.template: !Sub s3://${ConfigStackParameter.Value}/vendor_services/vendor-services.csv
        StorageDescriptor:
          Columns:
            - Name: vendor_name
              Type: string
            - Name: vendor_id
              Type: string
            - Name: service_name
              Type: string
            - Name: service_regex
              Type: string
            - Name: event_name
              Type: string
            - Name: contract_id
              Type: string
          Compressed: true
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${ConfigStackParameter.Value}/vendor_services/
          StoredAsSubDirectories: false
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              field.delim: ','
              skip.header.line.count: 1
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe

  ContractsMappingTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CalculationsDB
      TableInput:
        Name: btm_contracts_standardised
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: true
          storage.location.template: !Sub s3://${ConfigStackParameter.Value}/contracts/contracts.csv
        StorageDescriptor:
          Columns:
            - Name: id
              Type: string
            - Name: name
              Type: string
            - Name: vendor_id
              Type: string
          Compressed: true
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${ConfigStackParameter.Value}/contracts/
          StoredAsSubDirectories: false
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              field.delim: ','
              skip.header.line.count: 1
            SerializationLibrary: org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe

  TransactionsCuratedView:
    Type: Custom::AthenaView
    Properties:
      ServiceToken: !GetAtt CustomAthenaViewResourceFunction.Arn
      View:
        Database: !Ref CalculationsDB
        Name: btm_transactions_curated
        Query: |
          WITH btm_transactions_standardised_with_count
            AS (SELECT *,
                        "$path" path,
                        "SUM"(COALESCE(credits, 1))
                          OVER (
                            PARTITION BY event_name, vendor_id, year, month
                            ORDER BY year ASC, month ASC) month_event_count
                FROM   "btm_transactions_standardised"),
            btm_transactions_harmonised
            AS (SELECT txn.vendor_id,
                        txn.event_id,
                        txn.event_name,
                        txn.timestamp,
                        txn.year,
                        txn.month,
                        month_event_count,
                        ven.vendor_name,
                        ven.service_name,
                        contract.name contract_name,
                        (COALESCE(credits, 1) * rates.unit_price) transaction_price
                FROM (btm_transactions_standardised_with_count txn
                        LEFT JOIN "btm_vendor_service_standardised" ven 
                                ON (txn.event_name = ven.event_name)
                                  AND (txn.vendor_id = ven.vendor_id)
                        LEFT JOIN "btm_contracts_standardised" contract
                                ON (ven.contract_id = contract.id)
                        LEFT JOIN "btm_rates_standardised" rates
                          ON (txn.event_name = rates.event_name)
                            AND (txn.vendor_id = rates.vendor_id)
                            AND (txn.month_event_count BETWEEN rates.volumes_from AND COALESCE(rates.volumes_to, 9999999))
                            AND (txn.timestamp BETWEEN rates.effective_from AND COALESCE(rates.effective_to, "From_iso8601_timestamp"('2049-12-31')))))
          SELECT "MAX"(vendor_id)        vendor_id,
                "MAX"(vendor_name)       vendor_name,
                "MAX"(event_name)        event_name,
                "MAX"(service_name)      service_name,
                "MAX"(contract_name)     contract_name,
                "SUM"(transaction_price) price,
                "MAX"(month_event_count) quantity,
                month,
                year
          FROM   btm_transactions_harmonised
          GROUP  BY vendor_id,
                    service_name,
                    year,
                    month

        Workgroup: !Ref AthenaTransactionWorkgroup

  BillingAndTransactionsCuratedView:
    Type: Custom::AthenaView
    DependsOn:
      - InvoiceLineItemView
      - TransactionsCuratedView
    Properties:
      ServiceToken: !GetAtt CustomAthenaViewResourceFunction.Arn
      View:
        Database: !Ref CalculationsDB
        Name: btm_billing_and_transactions_curated
        Query: !Sub |
          SELECT
            COALESCE(txn.vendor_id, invoice.vendor_id) vendor_id
            , COALESCE(txn.vendor_name, invoice.vendor_name) vendor_name
            , COALESCE(txn.service_name, invoice.service_name) service_name
            , COALESCE(txn.contract_name, invoice.contract_name) contract_name
            , COALESCE(txn.year, invoice.year) year
            , COALESCE(txn.month, invoice.month) month
            , CONCAT('£', REGEXP_REPLACE(CAST(CAST(invoice.price AS DECIMAL(10,2)) AS VARCHAR), '(\d)(?=(\d{3})+\.)', '$1,')) billing_price_formatted
            , CONCAT('£', REGEXP_REPLACE(CAST(CAST(txn.price AS DECIMAL(10,2)) AS VARCHAR), '(\d)(?=(\d{3})+\.)', '$1,')) transaction_price_formatted
            , CONCAT('£', REGEXP_REPLACE(CAST(CAST((invoice.price - txn.price) AS decimal(10,2)) AS varchar), '(\d)(?=(\d{3})+\.)', '$1,')) price_difference
            , CONCAT('£', REGEXP_REPLACE(CAST(CAST((invoice.price + invoice.tax) AS decimal(10,2)) AS varchar), '(\d)(?=(\d{3})+\.)', '$1,')) billing_amount_with_tax
            , (CASE
                WHEN ((invoice.price = 0) AND (txn.price = 0)) THEN ${QueryMessageNoChargeForThisMonth}
                WHEN ((invoice.price IS NULL) AND (invoice.quantity IS NULL)) THEN ${QueryMessageInvoiceDataMissing}
                WHEN ((txn.price IS NULL) AND (txn.quantity IS NULL)) THEN ${QueryMessageTransactionDataMissing}
                WHEN (txn.price IS NULL) THEN ${QueryMessageRateCardDataMissing}
                ELSE (CASE WHEN (COALESCE(txn.price, 0) = 0) THEN (CASE WHEN (COALESCE(invoice.price, 0) = 0) THEN 0 ELSE null END) ELSE ((100 * (COALESCE(invoice.price, 0) - txn.price)) / txn.price) END) END) price_difference_percentage
          FROM
              (btm_transactions_curated txn
                FULL JOIN btm_billing_curated invoice ON
                      ((((txn.vendor_id = invoice.vendor_id) AND
                      (txn.event_name = invoice.event_name)) AND
                      (txn.year = invoice.year)) AND
                      (txn.month = invoice.month)))
        Workgroup: !Ref AthenaTransactionWorkgroup

  AthenaTransactionWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub ${AWS::StackName}-athena-workgroup
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: false
        ResultConfiguration:
          EncryptionConfiguration:
            EncryptionOption: SSE_KMS
            KmsKey: !GetAtt KmsKey.Arn
          OutputLocation:
            !Join ['', ['s3://', !Ref AthenaQueryResultsBucket, '/']]

  AthenaQueryResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-athena-query-results
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKey.Arn
            BucketKeyEnabled: true

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref GlobalLogBucket
        LogFilePrefix: athena-query-results-bucket/log
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 7
            Status: Enabled
