AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  CsvExtractFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for lambda driven by SQS
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-csv-extract-function
      Environment:
        Variables:
          DESTINATION_BUCKET: !Ref StorageBucket
          DESTINATION_FOLDER: btm_billing_standardised
          LOCAL_ENDPOINT:
            !If [IsLocal, 'http://s3.localhost.localstack.cloud:4566', '']
          POWERTOOLS_SERVICE_NAME: !Sub ${AWS::StackName}-csv-extract-function
      Events:
        CsvExtractEvent:
          Type: SQS
          Properties:
            FunctionResponseTypes:
              - ReportBatchItemFailures
            Queue: !GetAtt CsvExtractQueue.Arn
      Handler: csvExtract.handler
      KmsKeyArn: !GetAtt KmsKey.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
              Resource: !GetAtt CsvExtractQueue.Arn
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: !GetAtt KmsKey.Arn
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Join ['/', [!GetAtt RawInvoiceBucket.Arn, '*']]
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource:
                - !Join ['/', [!GetAtt StorageBucket.Arn, '*']]
      ReservedConcurrentExecutions: 1

  CsvExtractFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-csv-extract-function-alarm
      AlarmActions:
        - !GetAtt AlarmTopicParameter.Value
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CsvExtractFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0

  CsvExtractQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-csv-extract-queue
      KmsMasterKeyId: !GetAtt KmsKey.Arn
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CsvExtractQueueDeadLetterQueue.Arn
        maxReceiveCount: 3

  CsvExtractQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: SQS:SendMessage
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:*:*:${AWS::StackName}-raw-invoice # no reference as this needs be created before the bucket
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Resource: !GetAtt CsvExtractQueue.Arn
      Queues:
        - !Ref CsvExtractQueue

  CsvExtractQueueDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-csv-extract-dlq
      KmsMasterKeyId: !GetAtt KmsKey.Arn

  CsvExtractQueueDeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-csv-extract-dlq-alarm
      AlarmActions:
        - !GetAtt AlarmTopicParameter.Value
      Dimensions:
        - Name: QueueName
          Value: !GetAtt CsvExtractQueueDeadLetterQueue.QueueName
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 60
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      DatapointsToAlarm: 1
      EvaluationPeriods: 1
