AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  # CsvExtractFunction:

  CsvExtractQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-csv-extract-queue
      KmsMasterKeyId: !GetAtt KmsKey.Arn
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CsvExtractQueueDeadLetterQueue.Arn
        maxReceiveCount: 3

  CsvExtractQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: SQS:SendMessage
            Condition:
              ArnLike:
                aws:SourceArn: !Sub arn:aws:s3:*:*:${AWS::StackName}-raw-invoice # no reference as this needs be created before the bucket
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Resource: !GetAtt CsvExtractQueue.Arn
      Queues:
        - !Ref CsvExtractQueue

  # CsvExtractQueueDeadLetterQueue:

  # CsvExtractQueueDeadLetterQueueAlarm:
