AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ExtractFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for lambda driven by SQS
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        !Join ["-", [!Ref Prefix, !Ref Environment, extract-function]]
      Environment:
        Variables:
          TEXTRACT_ROLE: !GetAtt TextractRole.Arn
          TEXTRACT_SNS_TOPIC: !Ref AmazonTextractRawInvoiceDataTopic
      Events:
        ExtractEvent:
          Type: SQS
          Properties:
            FunctionResponseTypes:
              - ReportBatchItemFailures
            Queue: !GetAtt ExtractQueue.Arn
      Handler: extract.handler
      KmsKeyArn: !GetAtt KmsKey.Arn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
              Resource: !GetAtt ExtractQueue.Arn
            - Effect: Allow
              Action:
                - "textract:StartExpenseAnalysis" # https://docs.aws.amazon.com/textract/latest/dg/security_iam_id-based-policy-examples.html
              Resource: "*"
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: !GetAtt KmsKey.Arn
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Join ["/", [!GetAtt RawInvoicePdfBucket.Arn, "*"]]
      ReservedConcurrentExecutions: 10

  ExtractQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["-", [!Ref Prefix, !Ref Environment, extract-queue]]
      KmsMasterKeyId: !GetAtt KmsKey.Arn
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ExtractQueueDeadLetterQueue.Arn
        maxReceiveCount: 1

  ExtractQueueDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Join ["-", [!Ref Prefix, !Ref Environment, extract-dlq]]
      KmsMasterKeyId: !GetAtt KmsKey.Arn

  TextractRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "textract.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: "TextractRoleAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject*"
                Resource: !GetAtt RawInvoicePdfBucket.Arn
              - Effect: Allow
                Action:
                  - "sns:Publish"
                Resource: !Ref AmazonTextractRawInvoiceDataTopic
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey*
                  - kms:Encrypt
                Resource: !GetAtt KmsKey.Arn

  ExtractQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: SQS:SendMessage
            Condition:
              ArnLike:
                aws:SourceArn: arn:aws:s3:::*
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
            Effect: Allow
            Principal: "*"
            Resource: "*"
      Queues:
        - !Ref ExtractQueue
