ExtractFunction:
  # checkov:skip=CKV_AWS_117: VPC not needed for lambda
  # checkov:skip=CKV_AWS_116: DLQ not needed for lambda
  Type: AWS::Serverless::Function
  Properties:
    DeadLetterQueue:
      TargetArn: !GetAtt ExtractFunctionDeadLetterQueue.Arn
      Type: SQS
    Environment:
      Variables:
        TEXT_EXTRACT_ROLE: !GetAtt TextractRole.Arn # This is needed for the params for the textract call
        SNS_TOPIC: !Ref AmazonTextractRawInvoiceDataTopic # This topic name will come from BTM-202
    Events:
      ExtractEvent:
        Type: SQS
        Properties:
          Queue: !GetAtt ExtractQueue.Arn
    Handler: extract.handler
    KmsKeyArn: !GetAtt KmsKey.Arn
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Resource: !GetAtt ExtractQueue.Arn
          - Effect: Allow
            Action:
              - "sns:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - "textract:*"
            Resource: "*"
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey*
              - kms:Encrypt
            Resource: !GetAtt KmsKey.Arn
    ReservedConcurrentExecutions: 10

ExtractQueue:
  Type: AWS::SQS::Queue
  Properties:
    KmsMasterKeyId: !GetAtt KmsKey.Arn
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt ExtractQueueDeadLetterQueue.Arn
      maxReceiveCount: 1

ExtractQueueDeadLetterQueue:
  Type: AWS::SQS::Queue
  Properties:
    KmsMasterKeyId: !GetAtt KmsKey.Arn

TextractRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - "textract.amazonaws.com"
              - "lambda.amazonaws.com"
          Action:
            - "sts:AssumeRole"
    ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AWSLambdaExecute"
    Policies:
      - PolicyName: "TextractRoleAccess"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "sns:*"
              Resource: "*"
            - Effect: Allow
              Action:
                - "textract:*"
              Resource: "*"

ExtractQueuePolicy:
  Type: AWS::SQS::QueuePolicy
  Properties:
    PolicyDocument:
      Statement:
        - Action: SQS:SendMessage
          Condition:
            ArnLike:
              aws:SourceArn: arn:aws:s3:::*
            StringEquals:
              aws:SourceAccount: !Ref AWS::AccountId
          Effect: Allow
          Principal: "*"
          Resource: "*"
    Queues:
      - !Ref ExtractQueue
