ExtractFunction:
  # checkov:skip=CKV_AWS_117: VPC not needed for lambda
  Type: AWS::Serverless::Function
  Properties:
    DeadLetterQueue:
      TargetArn: !GetAtt ExtractFunctionDeadLetterQueue.Arn
      Type: SQS
    Environment:
      Variables:
        # EXTRACTION_HANDLER_RETURN_VALUE: done
        # EXTRACTION_HANDLER_THROW_ERROR: false
        TEXT_EXTRACT_ROLE: !GetAtt TextractRole.Arn # Is this needed?
        SNS_TOPIC: !Ref AmazonTextractSNSTopic # This topic name will come from BTM-202
    Role: !GetAtt TextractRole.Arn # See below
    Events:
      ExtractEvent:
        Type: SQS
        Properties:
          Queue: !GetAtt ExtractQueue.Arn
    Handler: extract.handler
    KmsKeyArn: !GetAtt KmsKey.Arn
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Resource: !GetAtt ExtractQueue.Arn
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey*
              - kms:Encrypt
            Resource: !GetAtt KmsKey.Arn
    ReservedConcurrentExecutions: 10

ExtractFunctionDeadLetterQueue:
  Type: AWS::SQS::Queue
  Properties:
    KmsMasterKeyId: !GetAtt KmsKey.Arn

ExtractQueue:
  Type: AWS::SQS::Queue
  Properties:
    KmsMasterKeyId: !GetAtt KmsKey.Arn
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt ExtractQueueDeadLetterQueue.Arn
      maxReceiveCount: 1

ExtractQueueDeadLetterQueue:
  Type: AWS::SQS::Queue
  Properties:
    KmsMasterKeyId: !GetAtt KmsKey.Arn

TextractRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: "2012-10-17"
      Statement:
        - Effect: "Allow"
          Principal:
            Service:
              - "textract.amazonaws.com"
              - "lambda.amazonaws.com"
          Action:
            - "sts:AssumeRole"
    ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AWSLambdaExecute"
    Policies:
      - PolicyName: "TextractRoleAccess"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "sns:*"
              Resource: "*"
            - Effect: Allow
              Action:
                - "textract:*"
              Resource: "*"
