FilterDeadLetterQueue:
  Type: AWS::SQS::Queue
  Properties:
    KmsMasterKeyId: !GetAtt KmsKey.Arn
    QueueName: filter-dead-letter-queue

# Does not seem to work locally: https://github.com/localstack/localstack/issues/7131
FilterDeadLetterQueueAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmActions:
      - !Ref AlarmTopic
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
      - Name: QueueName
        Value: !GetAtt FilterDeadLetterQueue.QueueName
    EvaluationPeriods: 1
    MetricName: NumberOfMessagesReceived
    Namespace: AWS/SQS
    Period: 1800
    Statistic: Sum
    Threshold: 0

FilterFunction:
  # checkov:skip=CKV_AWS_117: VPC not needed for lambda
  Type: AWS::Serverless::Function
  Properties:
    DeadLetterQueue:
      TargetArn: !GetAtt FilterFunctionDeadLetterQueue.Arn
      Type: SQS
    Events:
      FilterEvent:
        Type: SQS
        Properties:
          Queue: !GetAtt FilterQueue.Arn
    Environment:
      Variables:
        # checkov:skip=CKV_AWS_173: These environment variables do not require encryption.
        OUTPUT_QUEUE_URL: !Ref CleanQueue
        LOCAL_ENDPOINT: !If [IsLocal, "http://localhost:4566", ""]
    Handler: filter.handler
    Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
          - Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:ReceiveMessage
            Resource: !GetAtt FilterQueue.Arn
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource: !GetAtt CleanQueue.Arn
          - Effect: Allow
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey*
              - kms:Encrypt
            Resource: !GetAtt KmsKey.Arn
    ReservedConcurrentExecutions: 10

FilterFunctionAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmActions:
      - !Ref AlarmTopic
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
      - Name: FunctionName
        Value: !Ref FilterFunction
    EvaluationPeriods: 1
    MetricName: Errors
    Namespace: AWS/Lambda
    Period: 1800
    Statistic: Sum
    Threshold: 0

FilterFunctionDeadLetterQueue:
  Type: AWS::SQS::Queue
  Properties:
    KmsMasterKeyId: !GetAtt KmsKey.Arn
    QueueName: filter-function-dead-letter-queue

# Does not seem to work locally: https://github.com/localstack/localstack/issues/7131
FilterFunctionDeadLetterQueueAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmActions:
      - !Ref AlarmTopic
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
      - Name: QueueName
        Value: !GetAtt FilterFunctionDeadLetterQueue.QueueName
    EvaluationPeriods: 1
    MetricName: NumberOfMessagesReceived
    Namespace: AWS/SQS
    Period: 1800
    Statistic: Sum
    Threshold: 0

FilterQueue:
  Type: AWS::SQS::Queue
  Properties:
    KmsMasterKeyId: !GetAtt KmsKey.Arn
    RedrivePolicy:
      deadLetterTargetArn: !GetAtt FilterDeadLetterQueue.Arn
      maxReceiveCount: 1
    QueueName: filter-queue
