Resources:
  FrontEndApi:
    Type: AWS::Serverless::HttpApi
    Condition: IsLowerEnv
    Properties:
      AccessLogSettings:
        DestinationArn: !GetAtt FrontEndApiLogGroup.Arn
        Format: '{ "requestId":"$context.requestId", "requestTime":"$context.requestTime", "routeKey":"$context.routeKey", "status":"$context.status" }'

  FrontEndApiLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: IsLowerEnv
    Properties:
      KmsKeyId: !GetAtt KmsKey.Arn
      RetentionInDays: 90

  FrontEndFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for front end lambda
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Condition: IsLowerEnv
    Properties:
      Environment:
        Variables:
          # checkov:skip=CKV_AWS_173: These environment variables do not require encryption.
          CONFIG_BUCKET: !Sub di-btm-cfg-${AWS::StackName}
      FunctionName: !Sub ${AWS::StackName}-frontend-function
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref FrontEndApi
      Handler: frontend.handler
      ReservedConcurrentExecutions: 1
