Resources:
  FrontEndApi:
    Type: AWS::Serverless::HttpApi
    Condition: FrontEndApiEnabled
    Properties:
      AccessLogSettings:
        DestinationArn: !GetAtt FrontEndApiLogGroup.Arn
        Format: '{ "requestId":"$context.requestId", "requestTime":"$context.requestTime", "routeKey":"$context.routeKey", "status":"$context.status" }'
      Auth:
        Authorizers:
          LambdaAuthorizer:
            AuthorizerPayloadFormatVersion: '2.0'
            EnableFunctionDefaultPermissions: true
            EnableSimpleResponses: true
            FunctionArn: !GetAtt FrontEndAuthFunction.Arn
        DefaultAuthorizer: LambdaAuthorizer
      Domain:
        CertificateArn: !Ref FrontEndCertificateArn
        DomainName: !If
          - IsProduction
          - btm.account.gov.uk
          - !Sub btm.${Environment}.account.gov.uk
        Route53:
          HostedZoneName: !If
            - IsProduction
            - btm.account.gov.uk.
            - !Sub btm.${Environment}.account.gov.uk.

  FrontEndApiLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: IsLowerEnv
    Properties:
      KmsKeyId: !GetAtt KmsKey.Arn
      RetentionInDays: 90
      LogGroupName: !Sub '/aws/vendedlogs/${AWS::StackName}-FE-API-Log-Group'

  FrontEndAuthFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for front end lambda
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Condition: IsLowerEnv
    Properties:
      FunctionName: !Sub ${AWS::StackName}-frontend-auth-function
      Handler: frontendAuth.handler
      ReservedConcurrentExecutions: 10

  FrontEndFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for front end lambda
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Condition: IsLowerEnv
    Properties:
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
          CONFIG_BUCKET: !GetAtt ConfigStackParameter.Value
      FunctionName: !Sub ${AWS::StackName}-frontend-function
      Events:
        ProxyApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref FrontEndApi
      Handler: frontend.handler
      KmsKeyArn: !GetAtt KmsKey.Arn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: !GetAtt KmsKey.Arn
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::${ConfigStackParameter.Value}/*
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: '*'
              Condition:
                ForAnyValue:StringEquals:
                  kms:ResourceAliases: !Sub alias/key-${ConfigStackParameter.Value}-general
            - Effect: Allow
              Action: glue:GetTable
              Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action:
                - s3:AbortMultipartUpload
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListMultipartUploadParts
                - s3:PutObject
              Resource:
                - !GetAtt StorageBucket.Arn
                - !Sub ${StorageBucket.Arn}/*
                - !GetAtt AthenaQueryResultsBucket.Arn
                - !Sub ${AthenaQueryResultsBucket.Arn}/*
            - Effect: Allow
              Action:
                - athena:StartQueryExecution
                - athena:GetQueryExecution
                - athena:GetQueryResults
              Resource: !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary
      ReservedConcurrentExecutions: 10
