Resources:
  FrontEndApi:
    Type: AWS::Serverless::Api
    Condition: UseDomainName
    DependsOn:
      - FrontEndDomainName
      - FrontEndHostedZoneName
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt FrontEndApiLogGroup.Arn
        Format: '{ "requestId":"$context.requestId", "requestTime":"$context.requestTime", "routeKey":"$context.routeKey", "status":"$context.status" }'
      Auth:
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !GetAtt FrontEndAuthFunction.Arn
            FunctionPayloadType: REQUEST
            Identity: 
              Headers: 
                - Authorization
              QueryStrings:
                - code
                - state
        DefaultAuthorizer: LambdaAuthorizer
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      DefinitionBody: 
        openapi: 3.0.2
        info:
          title: DI Billing Frontend API
          description: A frontend for the Program Delivery Team to manage billing across Digital
            Identity
          version: '1.0'
        servers:
        - url: https://btm.account.gov.uk
        paths:
          "/":
            get:
              description: The home page
              responses:
                '200':
                  description: OK
                  text/html:
                    type: string
                    example: "<h1>Welcome to DI Billing</h1>"
      Domain:
        CertificateArn:
          Fn::ImportValue: !If
            - IsDev
            - !Sub di-btm-tooling-dev-frontend-certificate-arn
            - !Sub di-btm-tooling-${Environment}-frontend-certificate-arn
        DomainName: !GetAtt FrontEndDomainName.Value
        Route53:
          HostedZoneName: !GetAtt FrontEndHostedZoneName.Value
      MethodSettings:
        - ResourcePath: /
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300
      StageName: !Ref Environment
      TracingEnabled: true

  # A duplicate of FrontEndApi with no fixed domain name
  # Accessible in ephemeral environments
  FrontEndEphemeralApi:
    Type: AWS::Serverless::Api
    Condition: IsEphemeral
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt FrontEndApiLogGroup.Arn
        Format: '{ "requestId":"$context.requestId", "requestTime":"$context.requestTime", "routeKey":"$context.routeKey", "status":"$context.status" }'
      Auth:
        Authorizers:
          LambdaAuthorizer:
            FunctionArn: !GetAtt FrontEndAuthFunction.Arn
            FunctionPayloadType: REQUEST
            Identity: 
              Headers: 
                - Authorization
              QueryStrings:
                - code
                - state
        DefaultAuthorizer: LambdaAuthorizer
      CacheClusterEnabled: true
      CacheClusterSize: '0.5'
      DefinitionBody: 
        openapi: 3.0.2
        info:
          title: DI Billing Frontend API
          description: A frontend for the Program Delivery Team to manage billing across Digital
            Identity
          version: '1.0'
        servers:
        - url: https://btm.accounts.gov.uk
        paths:
          "/":
            get:
              description: The home page
              responses:
                '200':
                  description: OK
                  text/html:
                    type: string
                    example: "<h1>Welcome to DI Billing</h1>"
      MethodSettings:
        - ResourcePath: /
          HttpMethod: GET
          CachingEnabled: true
          CacheTtlInSeconds: 300
      StageName: !Ref Environment
      TracingEnabled: true

  FrontEndDomainName:
    Type: AWS::SSM::Parameter
    Condition: FrontEndEnabled
    Properties:
      Name: !Sub ${AWS::StackName}-frontend-domain-name
      Type: String
      Value: !If
        - IsProduction
        - btm.account.gov.uk
        - !If
          - IsDev
          - btm.dev.account.gov.uk
          - !Sub btm.${Environment}.account.gov.uk
      Description: !Sub Front end domain name used by app stack ${AWS::StackName}. Do not edit, managed by CloudFormation.

  FrontEndHostedZoneName:
    Type: AWS::SSM::Parameter
    Condition: FrontEndEnabled
    Properties:
      Name: !Sub ${AWS::StackName}-frontend-hosted-zone-name
      Type: String
      Value: !If
        - IsProduction
        - btm.account.gov.uk.
        - !If
          - IsDev
          - btm.dev.account.gov.uk.
          - !Sub btm.${Environment}.account.gov.uk.
      Description: !Sub Front end Route 53 Hosted Zone name used by app stack ${AWS::StackName}. Do not edit, managed by CloudFormation.

  FrontEndApiLogGroup:
    Type: AWS::Logs::LogGroup
    Condition: FrontEndEnabled
    Properties:
      KmsKeyId: !GetAtt KmsKey.Arn
      RetentionInDays: 90
      LogGroupName: !Sub '/aws/vendedlogs/${AWS::StackName}-FE-API-Log-Group'

  GoogleClientDetails:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: "The client id and client key for Sign In with Google"
      Name: "GoogleClientDetails"
      KmsKeyId: !Ref KmsKey

  FrontEndAuthFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for front end lambda
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    # checkov:skip=CKV_AWS_173: env var encryption, I'll remove this later
    Type: AWS::Serverless::Function
    Condition: FrontEndEnabled
    Properties:
      FunctionName: !Sub ${AWS::StackName}-frontend-auth-function
      Handler: frontendAuth.handler
      ReservedConcurrentExecutions: 10
      Environment:
        Variables:
          AWS_ACCOUNT_ID: AWS::AccountId
          GOOGLE_CLIENT_ID: "{{resolve:secretsmanager:GoogleClientDetails:SecretString:clientId}}"
          GOOGLE_CLIENT_SECRET: "{{resolve:secretsmanager:GoogleClientDetails:SecretString:clientSecret}}"

  FrontEndFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for front end lambda
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Condition: FrontEndEnabled
    Properties:
      Environment:
        Variables:
          STORAGE_BUCKET: !Ref StorageBucket
          CONFIG_BUCKET: !GetAtt ConfigStackParameter.Value
      FunctionName: !Sub ${AWS::StackName}-frontend-function
      Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            Path: /
            Method: '*'
      Handler: frontend.handler
      KmsKeyArn: !GetAtt KmsKey.Arn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: !GetAtt KmsKey.Arn
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::${ConfigStackParameter.Value}/*
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: '*'
              Condition:
                ForAnyValue:StringEquals:
                  kms:ResourceAliases: !Sub alias/key-${ConfigStackParameter.Value}-general
            - Effect: Allow
              Action: glue:GetTable
              Resource: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action:
                - s3:AbortMultipartUpload
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListMultipartUploadParts
                - s3:PutObject
              Resource:
                - !GetAtt StorageBucket.Arn
                - !Sub ${StorageBucket.Arn}/*
                - !GetAtt AthenaQueryResultsBucket.Arn
                - !Sub ${AthenaQueryResultsBucket.Arn}/*
            - Effect: Allow
              Action:
                - athena:StartQueryExecution
                - athena:GetQueryExecution
                - athena:GetQueryResults
              Resource: !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/primary
      ReservedConcurrentExecutions: 10
