AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  IntTestSupportFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for synchronously invoked lambda
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Condition: IsEnvWithAutoTests
    Properties:
      FunctionName: !Sub ${AWS::StackName}-int-test-support-function
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Sub ${AWS::StackName}-int-test-support-function
      Handler: intTestSupport.handler
      KmsKeyArn: !GetAtt KmsKey.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListMultipartUploadParts
                - s3:AbortMultipartUpload
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - !Sub arn:aws:s3:::${AWS::StackName}*
                - !Sub arn:aws:s3:::${ConfigStackParameter.Value}*
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: !GetAtt KmsKey.Arn
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: '*'
              Condition:
                ForAnyValue:StringEquals:
                  kms:ResourceAliases: !Sub alias/key-${ConfigStackParameter.Value}-general
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref TestTxMASNS
            - Effect: Allow
              Action:
                - sns:ListTopics
              Resource: '*'
            - Effect: Allow
              Action:
                - logs:FilterLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - athena:StartQueryExecution
                - athena:GetQueryExecution
                - athena:GetQueryResults
              Resource:
                - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${AthenaInvoiceWorkgroup}
                - !Sub arn:aws:athena:${AWS::Region}:${AWS::AccountId}:workgroup/${AthenaTransactionWorkgroup}
            - Effect: Allow
              Action:
                - glue:GetTable
                - glue:GetDatabase
              Resource: '*'
      ReservedConcurrentExecutions: 10

  AllowTestingContainerToInvoke:
    Type: AWS::Lambda::Permission
    Condition: IsEnvWithAutoTests
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref IntTestSupportFunction
      Principal: !Ref TestRoleArn
