AWSTemplateFormatVersion: '2010-09-09'

Resources:
  AthenaInvoiceWorkgroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub ${AWS::StackName}-athena-invoice-workgroup
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: false
        ResultConfiguration:
          EncryptionConfiguration:
            EncryptionOption: SSE_KMS
            KmsKey: !GetAtt KmsKey.Arn
          OutputLocation: !Sub s3://${AthenaInvoiceQueryResultsBucket}/

  AthenaInvoiceQueryResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-athena-invoice-query-results
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKey.Arn
            BucketKeyEnabled: true
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref GlobalLogBucket
        LogFilePrefix: athena-invoice-query-results-bucket/log
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 7
            Status: Enabled

  InvoiceLineItemTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref CalculationsDB
      TableInput:
        Name: btm_billing_standardised
        TableType: EXTERNAL_TABLE
        Parameters:
          has_encrypted_data: true
          partition_filtering.enabled: true
          projection.enabled: true
          projection.year.type: integer
          projection.year.range: 2005,2050
          projection.month.type: integer
          projection.month.digits: 2
          projection.month.range: 01,12
          storage.location.template:
            !Join [
              '',
              [
                's3://',
                !Ref StorageBucket,
                '/btm_invoice_data/${year}/${month}',
              ],
            ]
        PartitionKeys:
          - { Name: year, Type: string }
          - { Name: month, Type: string }
        StorageDescriptor:
          Columns:
            - Name: invoice_receipt_id
              Type: string
            - Name: vendor_id
              Type: string
            - Name: vendor_name
              Type: string
            - Name: total
              Type: decimal(12,4)
            - Name: invoice_receipt_date
              Type: date
            - Name: subtotal
              Type: decimal(12,4)
            - Name: due_date
              Type: date
            - Name: tax
              Type: decimal(12,4)
            - Name: tax_payer_id
              Type: string
            - Name: item_id
              Type: int
            - Name: item_description
              Type: string
            - Name: service_name
              Type: string
            - Name: contract_id
              Type: string
            - Name: unit_price
              Type: decimal(12,4)
            - Name: quantity
              Type: int
            - Name: price
              Type: decimal(12,4)
            - Name: event_name
              Type: string
            - Name: invoice_is_quarterly
              Type: boolean
          Compressed: 'true'
          InputFormat: org.apache.hadoop.mapred.TextInputFormat
          Location: !Sub s3://${StorageBucket}/btm_invoice_data/
          StoredAsSubDirectories: false
          OutputFormat: org.apache.hadoop.hive.ql.io.IgnoreKeyTextOutputFormat
          SerdeInfo:
            Parameters:
              field.delim: ''
              ignore.malformed.json: true
              serialiazation.format: 1
            SerializationLibrary: org.openx.data.jsonserde.JsonSerDe

  InvoiceLineItemView:
    Type: Custom::AthenaView
    DependsOn:
      - InvoiceLineItemTable
    Properties:
      ServiceToken: !GetAtt CustomAthenaViewResourceFunction.Arn
      View:
        Database: !Ref CalculationsDB
        Name: btm_billing_curated
        Query: |
          SELECT 
            btm.vendor_id,
            vendor_name,
            service_name,
            contract.id contract_id,
            contract.name contract_name,
            event_name,
            sum(quantity) AS quantity,
            btm.unit_price,
            sum(price) AS price,
            sum(tax) AS tax,
            year,
            month,
            btm.invoice_is_quarterly
          FROM btm_billing_standardised btm
          LEFT JOIN "btm_contracts_standardised" contract
                  ON (contract_id = contract.id)
          GROUP BY btm.vendor_id,btm.unit_price,vendor_name,contract.id,contract.name,service_name,event_name,year,month,btm.invoice_is_quarterly
        Workgroup: !Ref AthenaInvoiceWorkgroup
