AWSTemplateFormatVersion: '2010-09-09'

Resources:
  RawInvoicePdfBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [!Ref Prefix, !Ref Environment, raw-invoice-pdf ] ]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKey.Arn
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref RawInvoicePdfLogBucket
        LogFilePrefix: raw-invoice-pdf-bucket-log
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt ExtractQueue.Arn

  RawInvoicePdfLogBucket:
    # checkov:skip=CKV_AWS_18: This is the raw invoice pdf log bucket - no need for another
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [!Ref Prefix, !Ref Environment, raw-invoice-pdf-logs ] ]
      VersioningConfiguration:
        Status: Enabled
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKey.Arn
