AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AmazonTextractRawInvoiceDataTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-amazon-textract-raw-invoice-data-topic
      KmsMasterKeyId: !GetAtt KmsKey.Arn

  AmazonTextractRawInvoiceDataTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt RawInvoiceTextractDataQueue.Arn
      Protocol: sqs
      TopicArn: !Ref AmazonTextractRawInvoiceDataTopic

  RawInvoiceTextractDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-raw-invoice-textract-data
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKey.Arn
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref GlobalLogBucket
        LogFilePrefix: raw-invoice-textract-data-bucket/log
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.json'
            Queue: !GetAtt StandardisedInvoiceStorageQueue.Arn

  RawInvoiceTextractDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-raw-invoice-textract-data-queue
      KmsMasterKeyId: !GetAtt KmsKey.Arn
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RawInvoiceTextractDataDeadLetterQueue.Arn
        maxReceiveCount: 1

  RawInvoiceTextractDataQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - Action: SQS:SendMessage
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref AmazonTextractRawInvoiceDataTopic
            Effect: Allow
            Principal: '*'
            Resource: !GetAtt RawInvoiceTextractDataQueue.Arn
      Queues:
        - !Ref RawInvoiceTextractDataQueue

  RawInvoiceTextractDataDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-raw-invoice-textract-data-dlq
      KmsMasterKeyId: !GetAtt KmsKey.Arn

  RawInvoiceTextractDataDeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-raw-invoice-textract-data-dlq-alarm
      AlarmActions:
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      Metrics:
        - Id: messages
          MetricStat:
            Metric:
              Dimensions:
                - Name: QueueName
                  Value: !GetAtt RawInvoiceTextractDataDeadLetterQueue.QueueName
              MetricName: ApproximateNumberOfMessagesVisible
              Namespace: AWS/SQS
            Period: 1800
            Stat: Sum
          ReturnData: false
        - Id: messagesRate
          Expression: RATE(messages)
          ReturnData: true
      Threshold: 0

  RawInvoiceTextractDataStorageFunction:
    # checkov:skip=CKV_AWS_116: dead letter queue not needed for lambda
    # checkov:skip=CKV_AWS_117: VPC not needed for lambda
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-raw-textract-storage-function
      Environment:
        Variables:
          DESTINATION_BUCKET: !Ref RawInvoiceTextractDataBucket
      Events:
        RawInvoiceTextractDataEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RawInvoiceTextractDataQueue.Arn
      Handler: storeRawInvoiceTextractData.handler
      KmsKeyArn: !GetAtt KmsKey.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - sqs:DeleteMessage
                - sqs:GetQueueAttributes
                - sqs:ReceiveMessage
              Resource: !GetAtt RawInvoiceTextractDataQueue.Arn
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: !GetAtt KmsKey.Arn
            - Effect: Allow
              Action:
                - 'textract:GetExpenseAnalysis'
              Resource: '*'
            - Effect: Allow
              Action:
                - 's3:DeleteObject'
                - 's3:GetObject'
                - 's3:ListBucket'
                - 's3:PutObject'
              Resource:
                - !GetAtt RawInvoicePdfBucket.Arn
                - !Join ['/', [!GetAtt RawInvoicePdfBucket.Arn, '*']]
            - Effect: Allow
              Action:
                - 's3:PutObject'
              Resource:
                !Join ['/', [!GetAtt RawInvoiceTextractDataBucket.Arn, '*']]
      ReservedConcurrentExecutions: 10

  RawInvoiceTextractDataStorageFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-raw-textract-storage-function-alarm
      AlarmActions:
        - !Ref AlarmTopic
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref RawInvoiceTextractDataStorageFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 1800
      Statistic: Sum
      Threshold: 0
