AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SyntheticEventGenerationFunction:
    # checkov:skip=CKV_AWS_116: DLQ not needed for scheduled lambda that does not process events
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-synthetic-event-generation
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub di-btm-${Environment}-vpc-AWSServicesEndpointSecurityGroupId
        SubnetIds:
          - Fn::ImportValue: !Sub di-btm-${Environment}-vpc-PrivateSubnetIdA
          - Fn::ImportValue: !Sub di-btm-${Environment}-vpc-PrivateSubnetIdB
          - Fn::ImportValue: !Sub di-btm-${Environment}-vpc-PrivateSubnetIdC
      Environment:
        Variables:
          # checkov:skip=CKV_AWS_173: These environment variables do not require encryption.
          CONFIG_BUCKET: !GetAtt ConfigStackParameter.Value
          OUTPUT_QUEUE_URL: !Ref StorageQueue
          STORAGE_BUCKET: !Ref StorageBucket
          POWERTOOLS_SERVICE_NAME: !Sub ${AWS::StackName}-synthetic-event-generation-function
      Handler: syntheticEvents.handler
      KmsKeyArn: !GetAtt KmsKey.Arn
      Timeout: 180
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: !GetAtt KmsKey.Arn
            - Effect: Allow
              Action:
                - kms:Decrypt
                - kms:GenerateDataKey*
                - kms:Encrypt
              Resource: '*'
              Condition:
                ForAnyValue:StringEquals:
                  kms:ResourceAliases: !Sub alias/key-${ConfigStackParameter.Value}-general
            - Effect: Allow
              Action:
                - s3:AbortMultipartUpload
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:ListBucket
                - s3:ListBucketMultipartUploads
                - s3:ListMultipartUploadParts
                - s3:PutObject
              Resource:
                - !Sub arn:aws:s3:::${ConfigStackParameter.Value}
                - !Sub arn:aws:s3:::${ConfigStackParameter.Value}/*
                - !Sub arn:aws:s3:::${AWS::StackName}-storage
                - !Sub arn:aws:s3:::${AWS::StackName}-storage/*
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt StorageQueue.Arn
      ReservedConcurrentExecutions: 1

  SyntheticEventGenerationScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${AWS::StackName}-synthetic-event-generation-rule
      Description: Schedules SyntheticEventGenerationFunction to run once per month
      ScheduleExpression: cron(0 10 1 * ? *) # Schedule for 10 a.m. on the first of every month
      State: ENABLED
      Targets:
        - Arn: !GetAtt SyntheticEventGenerationFunction.Arn
          Id: SyntheticEventGenerationFunction

  LambdaPermissionForSyntheticEvents:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SyntheticEventGenerationFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt SyntheticEventGenerationScheduledRule.Arn

  LambdaPermissionForS3SyntheticEventGenerationFunction:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SyntheticEventGenerationFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${AWS::StackName}-storage

  SyntheticEventGenerationFunctionAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-synthetic-event-generation-function-alarm
      AlarmActions:
        - !GetAtt AlarmTopicParameter.Value
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref SyntheticEventGenerationFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 0
