AWSTemplateFormatVersion: '2010-09-09'

Resources:
  ValidatedInvoiceDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [!Ref Prefix, !Ref Environment, !Ref SubEnv, validated-invoice-data ] ]
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKey.Arn
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Ref ValidatedInvoiceDataLogBucket
        LogFilePrefix: validated-invoice-data-bucket-log

  ValidatedInvoiceDataLogBucket:
    # checkov:skip=CKV_AWS_18: This is the log bucket for the validated invoice data - no need for another
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [!Ref Prefix, !Ref Environment, !Ref SubEnv, validated-invoice-data-logs ] ]
      VersioningConfiguration:
        Status: Enabled
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt KmsKey.Arn
