AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ViewDataExtractionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-view-data-extraction-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: ViewDataExtractionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: !Sub arn:aws:logs:::${ConfigStackParameter.Value}/*

  ViewDataExtractionJob:
    Type: AWS::Glue::Job
    Properties:
      Command:
        Name: glueetl
        ScriptLocation: !Sub s3://${StorageBucket}/btm_extract_data/view-data-extract.py
        PythonVersion: 3
      MaxRetries: 0
      NumberOfWorkers: 2
      GlueVersion: 2.0
      Name: view-data-extraction-job1
      Role: !Ref ViewDataExtractionRole
      SecurityConfiguration: !Ref ViewDataExtractSecurityConfiguration
      WorkerType: Standard

  ViewDataExtractSecurityConfiguration:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      EncryptionConfiguration:
        CloudWatchEncryption:
          CloudWatchEncryptionMode: 'SSE-KMS'
          KmsKeyArn: !GetAtt KmsKey.Arn
        JobBookmarksEncryption:
          JobBookmarksEncryptionMode: 'CSE-KMS'
          KmsKeyArn: !GetAtt KmsKey.Arn
        S3Encryptions:
          - KmsKeyArn: !GetAtt KmsKey.Arn
            S3EncryptionMode: 'SSE-KMS'
      Name: ViewDataExtractSecurityConfiguration
