export enum Env {
  DESTINATION_BUCKET = "DESTINATION_BUCKET",
  DATABASE_NAME = "DATABASE_NAME",
  QUERY_RESULTS_BUCKET = "QUERY_RESULTS_BUCKET",
  POWERTOOLS_SERVICE_NAME = "POWERTOOLS_SERVICE_NAME",
}
