import { ValidEventName } from "./types";

export const VALID_EVENT_NAMES = new Set<ValidEventName>([
  "IPV_PASSPORT_CRI_REQUEST_SENT",
  "IPV_PASSPORT_CRI_RESPONSE_RECEIVED",
  "IPV_FRAUD_CRI_REQUEST_SENT",
  "IPV_FRAUD_CRI_THIRD_PARTY_REQUEST_ENDED",
  "IPV_ADDRESS_CRI_REQUEST_SENT",
  "IPV_ADDRESS_CRI_END",
  "IPV_KBV_CRI_REQUEST_SENT",
  "IPV_KBV_CRI_THIRD_PARTY_REQUEST_ENDED",
]);
