import { TestCases } from "./augmentTestCases";

export const testCases: TestCases = [
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_1",
    givenStatus: "BILLABLE",
    expectedPath: "happy",
    expectedEventId: "9656",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "IPV_C4_TEST1",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_1",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "happy",
    expectedEventId: "42758",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "IPV_C4_S_TEST1",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_1",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "74876",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE",
    expectedPath: "happy",
    expectedEventId: "49087",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "IPV_C4_S_TEST2",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_2",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "happy",
    expectedEventId: "85970",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "IPV_C4_SI_TEST2",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "happy",
    expectedEventId: "56013",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "IPV_C4_TEST3",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_2",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "30825",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "GOOP",
    givenStatus: "BILLABLE",
    expectedPath: "sad",
    expectedEventId: "94891",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "GOOP",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "sad",
    expectedEventId: "8199",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "GOOP",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "sad",
    expectedEventId: "76015",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "GOOP",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "44021",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_1",
    givenStatus: "BILLABLE",
    expectedPath: "happy",
    expectedEventId: "99178",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "IPV_C3_TEST1",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_1",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "happy",
    expectedEventId: "46561",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "IPV_C3_S_TEST1",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_1",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "47976",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE",
    expectedPath: "happy",
    expectedEventId: "23270",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "IPV_C3_S_TEST2",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_2",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "happy",
    expectedEventId: "89270",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "IPV_C3_SI_TEST2",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "happy",
    expectedEventId: "20736",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "IPV_C3_TEST3",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_2",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "14487",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "GOOP",
    givenStatus: "BILLABLE",
    expectedPath: "sad",
    expectedEventId: "50945",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "GOOP",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "sad",
    expectedEventId: "82622",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "GOOP",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "sad",
    expectedEventId: "84787",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "GOOP",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "59034",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_1",
    givenStatus: "BILLABLE",
    expectedPath: "sad",
    expectedEventId: "39350",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_1",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "sad",
    expectedEventId: "87104",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_1",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "sad",
    expectedEventId: "95403",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_1",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "21059",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE",
    expectedPath: "sad",
    expectedEventId: "53851",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_2",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "sad",
    expectedEventId: "14067",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "sad",
    expectedEventId: "83639",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_2",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "84863",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "GOOP",
    givenStatus: "BILLABLE",
    expectedPath: "sad",
    expectedEventId: "20220",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "GOOP",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "sad",
    expectedEventId: "48397",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "GOOP",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "sad",
    expectedEventId: "83969",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "GOOP",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "9382",
    expectedVendorId: "g.oo.p",
    expectedEventName: "unknown",
  },
];
