import { TestPaths } from "./addFauxDataToTestPaths";

export const testPaths: TestPaths = [
  {
    entity: "https://a.client4.co.uk",
    loa: "LEVEL_1",
    status: "BILLABLE",
    path: "happy",
    eventId: "9656",
    clientId: "client4",
    eventName: "IPV_C4_TEST1",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "LEVEL_1",
    status: "REPEAT-BILLABLE",
    path: "happy",
    eventId: "42758",
    clientId: "client4",
    eventName: "IPV_C4_S_TEST1",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "LEVEL_1",
    status: "GOOP",
    path: "sad",
    eventId: "74876",
    clientId: "client4",
    eventName: "unknown",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "LEVEL_2",
    status: "BILLABLE",
    path: "happy",
    eventId: "49087",
    clientId: "client4",
    eventName: "IPV_C4_S_TEST2",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "LEVEL_2",
    status: "REPEAT-BILLABLE",
    path: "happy",
    eventId: "85970",
    clientId: "client4",
    eventName: "IPV_C4_SI_TEST2",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "LEVEL_2",
    status: "BILLABLE-UPLIFT",
    path: "happy",
    eventId: "56013",
    clientId: "client4",
    eventName: "IPV_C4_TEST3",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "LEVEL_2",
    status: "GOOP",
    path: "sad",
    eventId: "30825",
    clientId: "client4",
    eventName: "unknown",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "GOOP",
    status: "BILLABLE",
    path: "sad",
    eventId: "94891",
    clientId: "client4",
    eventName: "unknown",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "GOOP",
    status: "REPEAT-BILLABLE",
    path: "sad",
    eventId: "8199",
    clientId: "client4",
    eventName: "unknown",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "GOOP",
    status: "BILLABLE-UPLIFT",
    path: "sad",
    eventId: "76015",
    clientId: "client4",
    eventName: "unknown",
  },
  {
    entity: "https://a.client4.co.uk",
    loa: "GOOP",
    status: "GOOP",
    path: "sad",
    eventId: "44021",
    clientId: "client4",
    eventName: "unknown",
  },
  {
    entity: "https://a.client3.eu",
    loa: "LEVEL_1",
    status: "BILLABLE",
    path: "happy",
    eventId: "99178",
    clientId: "client3",
    eventName: "IPV_C3_TEST1",
  },
  {
    entity: "https://a.client3.eu",
    loa: "LEVEL_1",
    status: "REPEAT-BILLABLE",
    path: "happy",
    eventId: "46561",
    clientId: "client3",
    eventName: "IPV_C3_S_TEST1",
  },
  {
    entity: "https://a.client3.eu",
    loa: "LEVEL_1",
    status: "GOOP",
    path: "sad",
    eventId: "47976",
    clientId: "client3",
    eventName: "unknown",
  },
  {
    entity: "https://a.client3.eu",
    loa: "LEVEL_2",
    status: "BILLABLE",
    path: "happy",
    eventId: "23270",
    clientId: "client3",
    eventName: "IPV_C3_S_TEST2",
  },
  {
    entity: "https://a.client3.eu",
    loa: "LEVEL_2",
    status: "REPEAT-BILLABLE",
    path: "happy",
    eventId: "89270",
    clientId: "client3",
    eventName: "IPV_C3_SI_TEST2",
  },
  {
    entity: "https://a.client3.eu",
    loa: "LEVEL_2",
    status: "BILLABLE-UPLIFT",
    path: "happy",
    eventId: "20736",
    clientId: "client3",
    eventName: "IPV_C3_TEST3",
  },
  {
    entity: "https://a.client3.eu",
    loa: "LEVEL_2",
    status: "GOOP",
    path: "sad",
    eventId: "14487",
    clientId: "client3",
    eventName: "unknown",
  },
  {
    entity: "https://a.client3.eu",
    loa: "GOOP",
    status: "BILLABLE",
    path: "sad",
    eventId: "50945",
    clientId: "client3",
    eventName: "unknown",
  },
  {
    entity: "https://a.client3.eu",
    loa: "GOOP",
    status: "REPEAT-BILLABLE",
    path: "sad",
    eventId: "82622",
    clientId: "client3",
    eventName: "unknown",
  },
  {
    entity: "https://a.client3.eu",
    loa: "GOOP",
    status: "BILLABLE-UPLIFT",
    path: "sad",
    eventId: "84787",
    clientId: "client3",
    eventName: "unknown",
  },
  {
    entity: "https://a.client3.eu",
    loa: "GOOP",
    status: "GOOP",
    path: "sad",
    eventId: "59034",
    clientId: "client3",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "LEVEL_1",
    status: "BILLABLE",
    path: "sad",
    eventId: "39350",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "LEVEL_1",
    status: "REPEAT-BILLABLE",
    path: "sad",
    eventId: "87104",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "LEVEL_1",
    status: "BILLABLE-UPLIFT",
    path: "sad",
    eventId: "95403",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "LEVEL_1",
    status: "GOOP",
    path: "sad",
    eventId: "21059",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "LEVEL_2",
    status: "BILLABLE",
    path: "sad",
    eventId: "53851",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "LEVEL_2",
    status: "REPEAT-BILLABLE",
    path: "sad",
    eventId: "14067",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "LEVEL_2",
    status: "BILLABLE-UPLIFT",
    path: "sad",
    eventId: "83639",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "LEVEL_2",
    status: "GOOP",
    path: "sad",
    eventId: "84863",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "GOOP",
    status: "BILLABLE",
    path: "sad",
    eventId: "20220",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "GOOP",
    status: "REPEAT-BILLABLE",
    path: "sad",
    eventId: "48397",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "GOOP",
    status: "BILLABLE-UPLIFT",
    path: "sad",
    eventId: "83969",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
  {
    entity: "https://g.oo.p",
    loa: "GOOP",
    status: "GOOP",
    path: "sad",
    eventId: "9382",
    clientId: "g.oo.p",
    eventName: "unknown",
  },
];
