import { TestCases } from "./augmentTestCases";

export const testCases: TestCases = [
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "happy",
    expectedEventId: "56013",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "VENDOR_4_EVENT_5",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "LEVEL_2",
    givenStatus: "GOOP",
    expectedPath: "sad",
    expectedEventId: "30825",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "Unknown",
  },
  {
    givenEntity: "https://a.vendor4.co.uk",
    givenLoa: "GOOP",
    givenStatus: "BILLABLE",
    expectedPath: "sad",
    expectedEventId: "94891",
    expectedVendorId: "vendor_testvendor4",
    expectedEventName: "Unknown",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_1",
    givenStatus: "BILLABLE",
    expectedPath: "happy",
    expectedEventId: "99178",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "VENDOR_3_EVENT_4",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "LEVEL_2",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "happy",
    expectedEventId: "89270",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "VENDOR_3_EVENT_6",
  },
  {
    givenEntity: "https://a.vendor3.eu",
    givenLoa: "GOOP",
    givenStatus: "REPEAT-BILLABLE",
    expectedPath: "sad",
    expectedEventId: "82622",
    expectedVendorId: "vendor_testvendor3",
    expectedEventName: "Unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_1",
    givenStatus: "BILLABLE",
    expectedPath: "sad",
    expectedEventId: "39350",
    expectedVendorId: "g.oo.p",
    expectedEventName: "Unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE",
    expectedPath: "sad",
    expectedEventId: "53851",
    expectedVendorId: "g.oo.p",
    expectedEventName: "Unknown",
  },
  {
    givenEntity: "https://g.oo.p",
    givenLoa: "LEVEL_2",
    givenStatus: "BILLABLE-UPLIFT",
    expectedPath: "sad",
    expectedEventId: "83639",
    expectedVendorId: "g.oo.p",
    expectedEventName: "Unknown",
  },
];
