name: Sonarcloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # sonarcloud:
  #   permissions:
  #     contents: write
  #     packages: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Get branch name
  #       id: branch-name
  #       uses: tj-actions/branch-names@v6
  #     - name: Assign branch value
  #       run: echo "branch=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV
  #     - name: Check out code
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Set up Node 16
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - run: npm ci
  #     - name: Run unit tests
  #       run: npm test
  #     - name: Run SonarCloud Scan
  #       uses: SonarSource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
