name: Tear down CF-stack created by manual workflow

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: ' Enter yourname or purpose all in lowercase of stack you want to delete'
        required: true

env:
  AWS_REGION: eu-west-2
  ENV_NAME: pr-${{ github.event.inputs.env_name }}

jobs:
  tear-down-cf-stack:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.DEV_GH_ACTIONS_TOOLING_ROLE_ARN }}
      - name: Tear down Cloudformation stack
        run: npm run sam:teardown